faluapp/falu-dotnet

- Directory.Build.targets
- src/Directory.Build.props
- src/Falu/Core/BasicListOptions.cs
- src/Falu/Core/IHasTags.cs
- src/Falu/Evaluations/EvaluationPatchModel.cs
- src/Falu/Evaluations/EvaluationsService.cs
- src/Falu/Events/WebhookEvent.cs
- src/Falu/Events/WebhookEventData.cs
- src/Falu/Extensions/EnumExtensions.cs
- src/Falu/Falu.csproj
- src/Falu/MessageStreams/MessageStreamPatchModel.cs
- src/Falu/MessageStrings.cs
- src/Falu/MessageTemplates/MessageTemplatePatchModel.cs
- src/Falu/Messages/MessagePatchModel.cs
- src/Falu/PaymentAuthorizations/PaymentAuthorization.cs
- src/Falu/PaymentAuthorizations/PaymentAuthorizationPatchModel.cs
- src/Falu/PaymentReversals/PaymentReversalFailureReason.cs
- src/Falu/PaymentReversals/PaymentReversalPatchModel.cs
- src/Falu/Payments/Payment.cs
- src/Falu/Payments/PaymentFailureReason.cs
- src/Falu/Payments/PaymentPatchModel.cs
- src/Falu/TransferReversals/TransferReversalFailureReason.cs
- src/Falu/TransferReversals/TransferReversalPatchModel.cs
- src/Falu/Transfers/TransferFailureReason.cs
- src/Falu/Transfers/TransferPatchModel.cs
- src/Falu/Webhooks/EventTypes.cs
- src/Falu/Webhooks/WebhookEndpointPatchModel.cs
- Make use of explicit names when working with `MultiPartFormDataContent`
- Update event for balance.
- Added `AmountOfBound` to all `*FailureReason` enums.
- `Phone` and `Password` are optional when creating an evaluation.
- Deprecated `Tags` in favour of `Metadata`.
> Updates 2021 07 14

- .github/dependabot.yml
- .github/workflows/build-release.yml
- .github/workflows/misspell.yml
Enable dependabot for GitHub actions and use simplified versions in workflow files
> Actions update

- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- src/FaluSdk/FaluClientOptionsPostConfigureOptions.cs
- src/FaluSdk/FaluSdk.csproj
- tests/FaluSdk.Tests/FaluSdk.Tests.csproj
- tests/FaluSdk.Tests/ServiceCollectionExtensionsTests.cs
Added support for pulling values for `FaluClientOptions` such as `ApiKey` and `Retries` from instances of `IConfiguration`
> Support usage of IConfiguration

- src/FaluSdk/Infrastructure/BaseService.cs
Add IdempotencyKey when not provided so that retries produce the same results
> Idempotency Key fix

- src/FaluSdk/Extensions/EnumExtensions.cs
- src/FaluSdk/Extensions/TypeExtensions.cs
- src/FaluSdk/FaluClientOptions.cs
- src/FaluSdk/MessageTemplates/MessageTemplatesService.cs
- src/FaluSdk/Messages/MessagesService.cs
- tests/FaluSdk.Tests/TypeExtensionsTests.cs
In this PR:
- `FaliClientOptions.SerializerOptions` is now internal.
- Values set for `MessageTemplateValidationRequest.Model` and `MessageSourceTemplate.Model` are validated to ensure they are objects.
> Validate template models

- README.md
- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- src/FaluSdk/FaluSdk.csproj
- tests/FaluSdk.Tests/FaluSdk.Tests.csproj
- tests/FaluSdk.Tests/ServiceCollectionExtensionsTests.cs
This PR removes support for `IConfiguration` added earlier, primarily to reduce the number of dependencies. Should the implementor/user need similar functionality, it can be added using:
```cs
services.AddFalu(options => Configuration.GetSection("Falu").Bind(options));
```
> Remove configuration support

- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- tests/FaluSdk.Tests/ServiceCollectionExtensionsTests.cs
Return `IHttpClientBuilder` instead of taking an `Action<IHttpClientBuilder>?` argument.
> Remove IHttpClientBuilder  action

- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- src/FaluSdk/FaluClient.cs
- tests/FaluSdk.Tests/ServiceCollectionExtensionsTests.cs
This PR replaces the use of `IOptions<T>` with `IOptionsSnapshot<T>` which is better since the client registered using a transient lifetime.
> Use IOptionsSnapshot

- .github/workflows/build-pr.yml
- .github/workflows/build-release.yml
- src/FaluSdk/Core/BaseServiceClient.cs
- src/FaluSdk/Events/EventUtility.cs
- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- src/FaluSdk/FaluClientOptions.cs
- src/FaluSdk/FaluSdk.csproj
- src/FaluSdk/Files/FilesServiceClient.cs
- src/FaluSdk/ResourceResponse.cs
- tests/FaluSdk.Tests/FaluSdk.Tests.csproj
Support `net6.0` and `net5.0` too with their specific API surfaces
> Multitarget

- src/FaluSdk/Core/QueryValues.cs
- src/FaluSdk/FaluClientOptions.cs
- tests/FaluSdk.Tests/QueryValuesTests.cs
URLs with arrays in the query should repeat the `key=value` pattern for each entry as that's what the server expects.
The SDK previously generated an erroneous:
```
/v1/events?sort=desc&count=100&type=evaluation.created,evaluation.failed,evaluation.completed,money_balances.updated,payment.updated
```
This should change to:
```
/v1/events?sort=desc&count=100&type=evaluation.created&type=evaluation.failed&type=evaluation.completed&type=money_balances.updated&type=payment.updated
```
> List of values for query should be added as multiple entries not combined

- .github/workflows/build-pr.yml
- .github/workflows/build-release.yml
- src/FaluSdk/FaluSdk.csproj
- tests/FaluSdk.Tests/FaluSdk.Tests.csproj
Remove .NET 5 support because it will EOL soon and netstandard2.1 will cover scenarios older than net6.0
> Remove net5.0

- src/FaluSdk/Extensions/IServiceCollectionExtensions.cs
- src/FaluSdk/FaluClientConfigureOptions.cs
- tests/FaluSdk.Tests/ServiceCollectionExtensionsTests.cs
Use `IValidateOptions<T>` to validate the options created
> Use IValidateOptions<T> to validate the options created

- src/FaluSdk/Core/BaseServiceClientOfT.cs
- src/FaluSdk/Core/ISupportsCanceling.cs
- src/FaluSdk/Evaluations/EvaluationsServiceClient.cs
- src/FaluSdk/FaluClient.cs
- src/FaluSdk/IdentityVerifications/IdentityVerificationsServiceClient.cs
- src/FaluSdk/MessageBatches/MessageBatch.cs
- src/FaluSdk/MessageBatches/MessageBatchCreateRequest.cs
- src/FaluSdk/MessageBatches/MessageBatchCreateRequestMessage.cs
- src/FaluSdk/MessageBatches/MessageBatchPatchModel.cs
- src/FaluSdk/MessageBatches/MessageBatchSchedule.cs
- src/FaluSdk/MessageBatches/MessageBatchesListOptions.cs
- src/FaluSdk/MessageBatches/MessageBatchesServiceClient.cs
- src/FaluSdk/Messages/Message.cs
- src/FaluSdk/Messages/MessagesListOptions.cs
- src/FaluSdk/Messages/MessagesServiceClient.cs
- src/FaluSdk/Webhooks/EventTypes.cs
- tests/FaluSdk.Tests/Clients/EvaluationsServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/IdentityVerificationsServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/MessageBatchesServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/MessagesServiceClientTests.cs
- Added support for message batches API hence mark `SendBatchAsync(...)` as obsolete in its favour.
- Added endpoints/methods for cancel and redact on identity verifications, evaluations and messages.
- Added `Batch`, `Segements`, `Sent` properties to `Message`.
- Added filters by `sent`, `batch`, and `stream ` when listing messages
> API updates

- src/FaluSdk/Messages/MessagesServiceClient.cs
- tests/FaluSdk.Tests/Clients/MessagesServiceClientTests.cs
Remove obsolete `SendAsync(...)` and `SendBatchAsync(...)` methods in `MessagesServiceClient`
> SDK Updates

- src/FaluSdk/FaluClientOptions.cs
- src/FaluSdk/MessageBatches/MessageBatchSchedule.cs
- src/FaluSdk/Messages/MessageCreateRequest.cs
- src/FaluSdk/Messages/MessageCreateRequestSchedule.cs
- src/FaluSdk/Messages/MessageSchedule.cs
- tests/FaluSdk.Tests/Clients/MessagesServiceClientTests.cs
- Update API version to `2022-09-01`.
- `To` in `MessageCreateRequest` now takes one destination only.
- Replace `TimeSpan` in models with `string` for ISO8601 duration.
> API Updates for Version 2022-09-01

- src/FaluSdk/Core/QueryValues.cs
- src/FaluSdk/MessageBatches/MessageBatchCreateRequest.cs
- src/FaluSdk/MessageBatches/MessageBatchCreateRequestMessage.cs
- src/FaluSdk/MessageBatches/MessageBatchesServiceClient.cs
- src/FaluSdk/MessageTemplates/MessageTemplatesListOptions.cs
- src/FaluSdk/Messages/MessageCreateRequest.cs
- tests/FaluSdk.Tests/Clients/CustomersServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/MessageBatchesServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/MessageSuppressionsServiceClientTests.cs
- tests/FaluSdk.Tests/Clients/MessageTemplatesServiceClientTests.cs
- Remove whitespaces and fix some typos.
- Added comments regarding the maximum number of messages in one API call
- Update XML comment on `MessageCreateRequest.To`.
- Unit test for `StatusAsync(...)` should make use of supplied options.
- Update example for message template identifier.
> Basic SDK updates

- src/FaluSdk/MessageTemplates/MessageTemplateModel.cs
- tests/FaluSdk.Tests/MessageTemplateModelTests.cs
- Reduce double allocations of template model during creation
- Added `Empty` property to reduce allocations of `MessageTemplateModel` in practical usage
- Added methods to convert a template to another object
- Test all conversion methods in `MessageTemplateModel`
> Updates to MessageTemplateModel logic

- src/FaluSdk/FaluSdk.csproj
This replaces `IsTrimmable` with `IsAotCompatible` which contains better analyzers. However, the reliance on `Tingle.Extensions.JsonPatch` may make it difficult to work with AoT but this will be removed in the next API version.
> AoT compatibility

- src/Falu/Falu.csproj
In #244, projects were renamed so no longer need to set `PackageId` in the project file.
> No need to set `PackageId` since the project rename

- falu-dotnet.sln
- src/Falu/Falu.csproj
`falu-cli` generates an assembly/executable named `falu` hence why the output for this project should be `FaluSdk`. Before #244, this was the output.
> Set `AssemblyName` to `FaluSdk` and `PackageId` to `Falu`
